--uncomment a single line to see a sample on a specific topic

require("Samples/image")
--require("Samples/textureAtlas")
--require("Samples/textureManager")
--require("Samples/movieclip")
--require("Samples/debugLines")
--require("Samples/dragndrop")
--require("Samples/textureHitTest")
--require("Samples/anim")
--require("Samples/flatten")
--require("Samples/clipArea")
--require("Samples/BlendModes/blendImages")
--require("Samples/BlendModes/blendQuads")
--require("Samples/BlendModes/blendDrawables")
--require("Samples/FileSystem/IO_functions")
--require("Samples/FileSystem/inifiles")
--require("Samples/FileSystem/xmlfiles")
--require("Samples/FileSystem/jsonfiles")
