-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:be55f955347cb2fc4e2ec8b14dd2335f:cd9897b8fa5f53704bab5730be7f5342:b74e9d71b94eaee4de272162c56c0493$
-- 

return {
	texture = 'PlanetCute_trimmed.png',
	frames = {
			{
				name = "Brown Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.530736, v0 = 0.252567, u1 = 0.618182, v1 = 0.501027 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Character Boy.png",
				spriteColorRect = { x = 17, y = 62, width = 67, height = 89 },
				uvRect = { u0 = 0.835498, v0 = 0.597536, u1 = 0.893506, v1 = 0.780287 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Character Cat Girl.png",
				spriteColorRect = { x = 16, y = 60, width = 69, height = 91 },
				uvRect = { u0 = 0.771429, v0 = 0.412731, u1 = 0.831169, v1 = 0.599589 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Character Horn Girl.png",
				spriteColorRect = { x = 7, y = 60, width = 77, height = 91 },
				uvRect = { u0 = 0.793939, v0 = 0.806982, u1 = 0.860606, v1 = 0.99384 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Character Pink Girl.png",
				spriteColorRect = { x = 12, y = 62, width = 77, height = 89 },
				uvRect = { u0 = 0.832035, v0 = 0.412731, u1 = 0.898701, v1 = 0.595483 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Character Princess Girl.png",
				spriteColorRect = { x = 13, y = 52, width = 75, height = 99 },
				uvRect = { u0 = 0.705628, v0 = 0.412731, u1 = 0.770563, v1 = 0.616016 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Chest Closed.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.530736, v0 = 0.00205339, u1 = 0.618182, v1 = 0.250513 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Chest Lid.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 85 },
				uvRect = { u0 = 0.795671, v0 = 0.23614, u1 = 0.883117, v1 = 0.410678 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Chest Open.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.442424, v0 = 0.50308, u1 = 0.52987, v1 = 0.75154 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Dirt Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.442424, v0 = 0.252567, u1 = 0.52987, v1 = 0.501027 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Door Tall Closed.png",
				spriteColorRect = { x = 0, y = 20, width = 101, height = 151 },
				uvRect = { u0 = 0.0891775, v0 = 0.671458, u1 = 0.176623, v1 = 0.98152 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Door Tall Open.png",
				spriteColorRect = { x = 0, y = 92, width = 101, height = 79 },
				uvRect = { u0 = 0.899567, v0 = 0.581109, u1 = 0.987013, v1 = 0.743326 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Enemy Bug.png",
				spriteColorRect = { x = 0, y = 77, width = 99, height = 77 },
				uvRect = { u0 = 0.619048, v0 = 0.839836, u1 = 0.704762, v1 = 0.997947 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Gem Blue.png",
				spriteColorRect = { x = 0, y = 57, width = 101, height = 113 },
				uvRect = { u0 = 0.795671, v0 = 0.00205339, u1 = 0.883117, v1 = 0.234086 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Gem Green.png",
				spriteColorRect = { x = 0, y = 57, width = 101, height = 113 },
				uvRect = { u0 = 0.707359, v0 = 0.00205339, u1 = 0.794805, v1 = 0.234086 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Gem Orange.png",
				spriteColorRect = { x = 0, y = 57, width = 101, height = 113 },
				uvRect = { u0 = 0.619048, v0 = 0.00205339, u1 = 0.706493, v1 = 0.234086 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Grass Block.png",
				spriteColorRect = { x = 0, y = 40, width = 101, height = 131 },
				uvRect = { u0 = 0.177489, v0 = 0.00205339, u1 = 0.264935, v1 = 0.271047 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Heart.png",
				spriteColorRect = { x = 7, y = 47, width = 89, height = 91 },
				uvRect = { u0 = 0.757576, v0 = 0.61807, u1 = 0.834632, v1 = 0.804928 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Key.png",
				spriteColorRect = { x = 17, y = 56, width = 59, height = 99 },
				uvRect = { u0 = 0.705628, v0 = 0.61807, u1 = 0.75671, v1 = 0.821355 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Plain Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.442424, v0 = 0.00205339, u1 = 0.52987, v1 = 0.250513 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp East.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.530736, v0 = 0.749487, u1 = 0.618182, v1 = 0.99384 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp North.png",
				spriteColorRect = { x = 0, y = 90, width = 101, height = 81 },
				uvRect = { u0 = 0.899567, v0 = 0.412731, u1 = 0.987013, v1 = 0.579055 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp South.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.354113, v0 = 0.50308, u1 = 0.441558, v1 = 0.75154 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp West.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.530736, v0 = 0.50308, u1 = 0.618182, v1 = 0.747433 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Rock.png",
				spriteColorRect = { x = 1, y = 65, width = 99, height = 99 },
				uvRect = { u0 = 0.619048, v0 = 0.634497, u1 = 0.704762, v1 = 0.837782 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof East.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.442424, v0 = 0.753593, u1 = 0.52987, v1 = 0.997947 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof North East.png",
				spriteColorRect = { x = 0, y = 86, width = 101, height = 85 },
				uvRect = { u0 = 0.707359, v0 = 0.23614, u1 = 0.794805, v1 = 0.410678 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof North West.png",
				spriteColorRect = { x = 0, y = 86, width = 101, height = 85 },
				uvRect = { u0 = 0.619048, v0 = 0.23614, u1 = 0.706493, v1 = 0.410678 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof North.png",
				spriteColorRect = { x = 0, y = 90, width = 101, height = 81 },
				uvRect = { u0 = 0.705628, v0 = 0.823409, u1 = 0.793074, v1 = 0.989733 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof South East.png",
				spriteColorRect = { x = 0, y = 48, width = 101, height = 123 },
				uvRect = { u0 = 0.265801, v0 = 0.256674, u1 = 0.353247, v1 = 0.50924 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof South West.png",
				spriteColorRect = { x = 0, y = 48, width = 101, height = 123 },
				uvRect = { u0 = 0.265801, v0 = 0.00205339, u1 = 0.353247, v1 = 0.25462 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof South.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.354113, v0 = 0.252567, u1 = 0.441558, v1 = 0.501027 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof West.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.354113, v0 = 0.753593, u1 = 0.441558, v1 = 0.997947 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Selector.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000865801, v0 = 0.00205339, u1 = 0.0883117, v1 = 0.353183 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow East.png",
				spriteColorRect = { x = 80, y = 50, width = 21, height = 81 },
				uvRect = { u0 = 0.972294, v0 = 0.00205339, u1 = 0.990476, v1 = 0.168378 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow North East.png",
				spriteColorRect = { x = 80, y = 50, width = 21, height = 51 },
				uvRect = { u0 = 0.972294, v0 = 0.277207, u1 = 0.990476, v1 = 0.38193 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow North West.png",
				spriteColorRect = { x = 0, y = 50, width = 51, height = 51 },
				uvRect = { u0 = 0.951515, v0 = 0.790554, u1 = 0.995671, v1 = 0.895277 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow North.png",
				spriteColorRect = { x = 0, y = 9, width = 101, height = 91 },
				uvRect = { u0 = 0.883983, v0 = 0.223819, u1 = 0.971429, v1 = 0.410678 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow Side West.png",
				spriteColorRect = { x = 0, y = 130, width = 51, height = 41 },
				uvRect = { u0 = 0.906493, v0 = 0.897331, u1 = 0.950649, v1 = 0.98152 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow South East.png",
				spriteColorRect = { x = 80, y = 80, width = 21, height = 51 },
				uvRect = { u0 = 0.972294, v0 = 0.170431, u1 = 0.990476, v1 = 0.275154 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow South West.png",
				spriteColorRect = { x = 0, y = 80, width = 51, height = 51 },
				uvRect = { u0 = 0.906493, v0 = 0.790554, u1 = 0.950649, v1 = 0.895277 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow South.png",
				spriteColorRect = { x = 0, y = 79, width = 101, height = 21 },
				uvRect = { u0 = 0.894372, v0 = 0.74538, u1 = 0.981818, v1 = 0.788501 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow West.png",
				spriteColorRect = { x = 0, y = 50, width = 51, height = 81 },
				uvRect = { u0 = 0.861472, v0 = 0.790554, u1 = 0.905628, v1 = 0.956879 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "SpeechBubble.png",
				spriteColorRect = { x = 0, y = 64, width = 101, height = 107 },
				uvRect = { u0 = 0.883983, v0 = 0.00205339, u1 = 0.971429, v1 = 0.221766 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Star.png",
				spriteColorRect = { x = 0, y = 51, width = 101, height = 101 },
				uvRect = { u0 = 0.177489, v0 = 0.790554, u1 = 0.264935, v1 = 0.997947 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Stone Block Tall.png",
				spriteColorRect = { x = 0, y = 8, width = 101, height = 163 },
				uvRect = { u0 = 0.0891775, v0 = 0.00205339, u1 = 0.176623, v1 = 0.336756 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Stone Block.png",
				spriteColorRect = { x = 0, y = 48, width = 101, height = 123 },
				uvRect = { u0 = 0.177489, v0 = 0.535934, u1 = 0.264935, v1 = 0.788501 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Tree Short.png",
				spriteColorRect = { x = 0, y = 55, width = 99, height = 107 },
				uvRect = { u0 = 0.619048, v0 = 0.412731, u1 = 0.704762, v1 = 0.632444 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Tree Tall.png",
				spriteColorRect = { x = 0, y = 31, width = 101, height = 137 },
				uvRect = { u0 = 0.000865801, v0 = 0.700205, u1 = 0.0883117, v1 = 0.98152 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Tree Ugly.png",
				spriteColorRect = { x = 0, y = 54, width = 101, height = 115 },
				uvRect = { u0 = 0.265801, v0 = 0.761807, u1 = 0.353247, v1 = 0.997947 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Wall Block Tall.png",
				spriteColorRect = { x = 0, y = 4, width = 101, height = 167 },
				uvRect = { u0 = 0.000865801, v0 = 0.355236, u1 = 0.0883117, v1 = 0.698152 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Wall Block.png",
				spriteColorRect = { x = 0, y = 44, width = 101, height = 127 },
				uvRect = { u0 = 0.177489, v0 = 0.273101, u1 = 0.264935, v1 = 0.533881 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Water Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.354113, v0 = 0.00205339, u1 = 0.441558, v1 = 0.250513 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Window Tall.png",
				spriteColorRect = { x = 0, y = 10, width = 101, height = 161 },
				uvRect = { u0 = 0.0891775, v0 = 0.338809, u1 = 0.176623, v1 = 0.669405 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Wood Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.265801, v0 = 0.511294, u1 = 0.353247, v1 = 0.759754 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

