-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:2106caff0c626f31d9b0042614ff89ae$
-- 

return {
	texture = 'PlanetCute.png',
	frames = {
			{
				name = "Brown Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.000488281, u1 = 0.199219, v1 = 0.0839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Character Boy.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.000488281, u1 = 0.398438, v1 = 0.0839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Character Cat Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.000488281, u1 = 0.597656, v1 = 0.0839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Character Horn Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.000488281, u1 = 0.796875, v1 = 0.0839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Character Pink Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.000488281, u1 = 0.996094, v1 = 0.0839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Character Princess Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.0844727, u1 = 0.199219, v1 = 0.167969 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Chest Closed.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.0844727, u1 = 0.398438, v1 = 0.167969 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Chest Lid.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.0844727, u1 = 0.597656, v1 = 0.167969 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Chest Open.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.0844727, u1 = 0.796875, v1 = 0.167969 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Dirt Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.0844727, u1 = 0.996094, v1 = 0.167969 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Door Tall Closed.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.168457, u1 = 0.199219, v1 = 0.251953 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Door Tall Open.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.168457, u1 = 0.398438, v1 = 0.251953 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Enemy Bug.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.168457, u1 = 0.597656, v1 = 0.251953 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Gem Blue.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.168457, u1 = 0.796875, v1 = 0.251953 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Gem Green.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.168457, u1 = 0.996094, v1 = 0.251953 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Gem Orange.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.252441, u1 = 0.199219, v1 = 0.335938 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Grass Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.252441, u1 = 0.398438, v1 = 0.335938 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Heart.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.252441, u1 = 0.597656, v1 = 0.335938 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Key.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.252441, u1 = 0.796875, v1 = 0.335938 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Plain Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.252441, u1 = 0.996094, v1 = 0.335938 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Ramp East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.336426, u1 = 0.199219, v1 = 0.419922 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Ramp North.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.336426, u1 = 0.398438, v1 = 0.419922 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Ramp South.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.336426, u1 = 0.597656, v1 = 0.419922 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Ramp West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.336426, u1 = 0.796875, v1 = 0.419922 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Rock.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.336426, u1 = 0.996094, v1 = 0.419922 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.42041, u1 = 0.199219, v1 = 0.503906 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof North East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.42041, u1 = 0.398438, v1 = 0.503906 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof North West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.42041, u1 = 0.597656, v1 = 0.503906 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof North.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.42041, u1 = 0.796875, v1 = 0.503906 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof South East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.42041, u1 = 0.996094, v1 = 0.503906 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof South West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.504395, u1 = 0.199219, v1 = 0.587891 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof South.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.504395, u1 = 0.398438, v1 = 0.587891 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.504395, u1 = 0.597656, v1 = 0.587891 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Selector.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.504395, u1 = 0.796875, v1 = 0.587891 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.504395, u1 = 0.996094, v1 = 0.587891 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow North East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.588379, u1 = 0.199219, v1 = 0.671875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow North West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.588379, u1 = 0.398438, v1 = 0.671875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow North.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.588379, u1 = 0.597656, v1 = 0.671875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow Side West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.588379, u1 = 0.796875, v1 = 0.671875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow South East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.588379, u1 = 0.996094, v1 = 0.671875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow South West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.672363, u1 = 0.199219, v1 = 0.755859 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow South.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.672363, u1 = 0.398438, v1 = 0.755859 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.672363, u1 = 0.597656, v1 = 0.755859 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SpeechBubble.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.672363, u1 = 0.796875, v1 = 0.755859 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Star.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.672363, u1 = 0.996094, v1 = 0.755859 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Stone Block Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.756348, u1 = 0.199219, v1 = 0.839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Stone Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.756348, u1 = 0.398438, v1 = 0.839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Tree Short.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.756348, u1 = 0.597656, v1 = 0.839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Tree Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.756348, u1 = 0.796875, v1 = 0.839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Tree Ugly.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.756348, u1 = 0.996094, v1 = 0.839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Wall Block Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.00195312, v0 = 0.840332, u1 = 0.199219, v1 = 0.923828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Wall Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.201172, v0 = 0.840332, u1 = 0.398438, v1 = 0.923828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Water Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.400391, v0 = 0.840332, u1 = 0.597656, v1 = 0.923828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Window Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.599609, v0 = 0.840332, u1 = 0.796875, v1 = 0.923828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Wood Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.798828, v0 = 0.840332, u1 = 0.996094, v1 = 0.923828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

