-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:88e65396cf529e372af7f0f29e4961f3:cd9897b8fa5f53704bab5730be7f5342:a26003f68db1b601eedee18feecd0c17$
-- 

return {
	texture = 'PlanetCute_optimized.png',
	frames = {
			{
				name = "Brown Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.439381, v0 = 0.498982, u1 = 0.526225, v1 = 0.745418 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Character Boy.png",
				spriteColorRect = { x = 17, y = 62, width = 67, height = 89 },
				uvRect = { u0 = 0.869304, v0 = 0.682281, u1 = 0.94583, v1 = 0.818737 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Character Cat Girl.png",
				spriteColorRect = { x = 16, y = 60, width = 69, height = 91 },
				uvRect = { u0 = 0.702494, v0 = 0.661914, u1 = 0.780739, v1 = 0.802444 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Character Horn Girl.png",
				spriteColorRect = { x = 7, y = 60, width = 77, height = 91 },
				uvRect = { u0 = 0.700774, v0 = 0.804481, u1 = 0.77902, v1 = 0.961303 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Character Pink Girl.png",
				spriteColorRect = { x = 12, y = 62, width = 77, height = 89 },
				uvRect = { u0 = 0.867584, v0 = 0.820774, u1 = 0.94411, v1 = 0.977597 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Character Princess Girl.png",
				spriteColorRect = { x = 13, y = 52, width = 75, height = 99 },
				uvRect = { u0 = 0.781599, v0 = 0.718941, u1 = 0.866724, v1 = 0.87169 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Chest Closed.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.351677, v0 = 0.747454, u1 = 0.438521, v1 = 0.99389 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Chest Lid.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 85 },
				uvRect = { u0 = 0.788478, v0 = 0.376782, u1 = 0.875322, v1 = 0.549898 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Chest Open.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.527085, v0 = 0.00203666, u1 = 0.61393, v1 = 0.248473 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Dirt Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.439381, v0 = 0.250509, u1 = 0.526225, v1 = 0.496945 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Door Tall Closed.png",
				spriteColorRect = { x = 0, y = 20, width = 101, height = 151 },
				uvRect = { u0 = 0.176268, v0 = 0.00203666, u1 = 0.263113, v1 = 0.309572 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Door Tall Open.png",
				spriteColorRect = { x = 0, y = 92, width = 101, height = 79 },
				uvRect = { u0 = 0.877902, v0 = 0.177189, u1 = 0.964746, v1 = 0.338086 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Enemy Bug.png",
				spriteColorRect = { x = 0, y = 77, width = 99, height = 77 },
				uvRect = { u0 = 0.877902, v0 = 0.340122, u1 = 0.963027, v1 = 0.496945 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Gem Blue.png",
				spriteColorRect = { x = 0, y = 57, width = 101, height = 113 },
				uvRect = { u0 = 0.527085, v0 = 0.731161, u1 = 0.61393, v1 = 0.961303 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Gem Green.png",
				spriteColorRect = { x = 0, y = 57, width = 101, height = 113 },
				uvRect = { u0 = 0.702494, v0 = 0.00203666, u1 = 0.789338, v1 = 0.232179 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Gem Orange.png",
				spriteColorRect = { x = 0, y = 57, width = 101, height = 113 },
				uvRect = { u0 = 0.614789, v0 = 0.246436, u1 = 0.701634, v1 = 0.476578 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Grass Block.png",
				spriteColorRect = { x = 0, y = 40, width = 101, height = 131 },
				uvRect = { u0 = 0.0885641, v0 = 0.665988, u1 = 0.175408, v1 = 0.93279 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Heart.png",
				spriteColorRect = { x = 7, y = 47, width = 89, height = 91 },
				uvRect = { u0 = 0.876182, v0 = 0.498982, u1 = 0.954428, v1 = 0.680244 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Key.png",
				spriteColorRect = { x = 17, y = 56, width = 59, height = 99 },
				uvRect = { u0 = 0.77988, v0 = 0.873727, u1 = 0.865004, v1 = 0.99389 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Plain Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.351677, v0 = 0.498982, u1 = 0.438521, v1 = 0.745418 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp East.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.439381, v0 = 0.747454, u1 = 0.526225, v1 = 0.989817 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp North.png",
				spriteColorRect = { x = 0, y = 90, width = 101, height = 81 },
				uvRect = { u0 = 0.781599, v0 = 0.551935, u1 = 0.868444, v1 = 0.716904 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp South.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.439381, v0 = 0.00203666, u1 = 0.526225, v1 = 0.248473 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Ramp West.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.614789, v0 = 0.00203666, u1 = 0.701634, v1 = 0.244399 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Rock.png",
				spriteColorRect = { x = 1, y = 65, width = 99, height = 99 },
				uvRect = { u0 = 0.614789, v0 = 0.698574, u1 = 0.699914, v1 = 0.900204 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof East.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.527085, v0 = 0.250509, u1 = 0.61393, v1 = 0.492872 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof North East.png",
				spriteColorRect = { x = 0, y = 86, width = 101, height = 85 },
				uvRect = { u0 = 0.877902, v0 = 0.00203666, u1 = 0.964746, v1 = 0.175153 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof North West.png",
				spriteColorRect = { x = 0, y = 86, width = 101, height = 85 },
				uvRect = { u0 = 0.176268, v0 = 0.824847, u1 = 0.263113, v1 = 0.997963 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof North.png",
				spriteColorRect = { x = 0, y = 90, width = 101, height = 81 },
				uvRect = { u0 = 0.790198, v0 = 0.209776, u1 = 0.877042, v1 = 0.374745 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof South East.png",
				spriteColorRect = { x = 0, y = 48, width = 101, height = 123 },
				uvRect = { u0 = 0.263972, v0 = 0.254582, u1 = 0.350817, v1 = 0.505092 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof South West.png",
				spriteColorRect = { x = 0, y = 48, width = 101, height = 123 },
				uvRect = { u0 = 0.176268, v0 = 0.572301, u1 = 0.263113, v1 = 0.822811 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof South.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.351677, v0 = 0.250509, u1 = 0.438521, v1 = 0.496945 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Roof West.png",
				spriteColorRect = { x = 0, y = 52, width = 101, height = 119 },
				uvRect = { u0 = 0.263972, v0 = 0.755601, u1 = 0.350817, v1 = 0.997963 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Selector.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000859845, v0 = 0.00203666, u1 = 0.0877042, v1 = 0.350305 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow East.png",
				spriteColorRect = { x = 80, y = 50, width = 21, height = 81 },
				uvRect = { u0 = 0.614789, v0 = 0.90224, u1 = 0.684437, v1 = 0.94501 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Shadow North East.png",
				spriteColorRect = { x = 80, y = 50, width = 21, height = 51 },
				uvRect = { u0 = 0.965606, v0 = 0.107943, u1 = 0.983663, v1 = 0.211813 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow North West.png",
				spriteColorRect = { x = 0, y = 50, width = 51, height = 51 },
				uvRect = { u0 = 0.94669, v0 = 0.771894, u1 = 0.990542, v1 = 0.875764 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow North.png",
				spriteColorRect = { x = 0, y = 9, width = 101, height = 91 },
				uvRect = { u0 = 0.702494, v0 = 0.454175, u1 = 0.780739, v1 = 0.659878 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Shadow Side West.png",
				spriteColorRect = { x = 0, y = 130, width = 51, height = 41 },
				uvRect = { u0 = 0.963886, v0 = 0.340122, u1 = 0.99914, v1 = 0.443992 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Shadow South East.png",
				spriteColorRect = { x = 80, y = 80, width = 21, height = 51 },
				uvRect = { u0 = 0.965606, v0 = 0.00203666, u1 = 0.983663, v1 = 0.105906 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow South West.png",
				spriteColorRect = { x = 0, y = 80, width = 51, height = 51 },
				uvRect = { u0 = 0.955288, v0 = 0.665988, u1 = 0.99914, v1 = 0.769857 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow South.png",
				spriteColorRect = { x = 0, y = 79, width = 101, height = 21 },
				uvRect = { u0 = 0.0885641, v0 = 0.934827, u1 = 0.175408, v1 = 0.977597 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Shadow West.png",
				spriteColorRect = { x = 0, y = 50, width = 51, height = 81 },
				uvRect = { u0 = 0.955288, v0 = 0.498982, u1 = 0.99914, v1 = 0.663951 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "SpeechBubble.png",
				spriteColorRect = { x = 0, y = 64, width = 101, height = 107 },
				uvRect = { u0 = 0.614789, v0 = 0.478615, u1 = 0.701634, v1 = 0.696538 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Star.png",
				spriteColorRect = { x = 0, y = 51, width = 101, height = 101 },
				uvRect = { u0 = 0.790198, v0 = 0.00203666, u1 = 0.877042, v1 = 0.207739 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Stone Block Tall.png",
				spriteColorRect = { x = 0, y = 8, width = 101, height = 163 },
				uvRect = { u0 = 0.0885641, v0 = 0.00203666, u1 = 0.175408, v1 = 0.334012 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Stone Block.png",
				spriteColorRect = { x = 0, y = 48, width = 101, height = 123 },
				uvRect = { u0 = 0.263972, v0 = 0.00203666, u1 = 0.350817, v1 = 0.252546 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Tree Short.png",
				spriteColorRect = { x = 0, y = 55, width = 99, height = 107 },
				uvRect = { u0 = 0.702494, v0 = 0.234216, u1 = 0.787618, v1 = 0.452138 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Tree Tall.png",
				spriteColorRect = { x = 0, y = 31, width = 101, height = 137 },
				uvRect = { u0 = 0.000859845, v0 = 0.694501, u1 = 0.0877042, v1 = 0.973523 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Tree Ugly.png",
				spriteColorRect = { x = 0, y = 54, width = 101, height = 115 },
				uvRect = { u0 = 0.527085, v0 = 0.494908, u1 = 0.61393, v1 = 0.729124 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Wall Block Tall.png",
				spriteColorRect = { x = 0, y = 4, width = 101, height = 167 },
				uvRect = { u0 = 0.000859845, v0 = 0.352342, u1 = 0.0877042, v1 = 0.692464 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Wall Block.png",
				spriteColorRect = { x = 0, y = 44, width = 101, height = 127 },
				uvRect = { u0 = 0.176268, v0 = 0.311609, u1 = 0.263113, v1 = 0.570265 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Water Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.263972, v0 = 0.507128, u1 = 0.350817, v1 = 0.753564 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Window Tall.png",
				spriteColorRect = { x = 0, y = 10, width = 101, height = 161 },
				uvRect = { u0 = 0.0885641, v0 = 0.336049, u1 = 0.175408, v1 = 0.663951 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Wood Block.png",
				spriteColorRect = { x = 0, y = 50, width = 101, height = 121 },
				uvRect = { u0 = 0.351677, v0 = 0.00203666, u1 = 0.438521, v1 = 0.248473 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

