-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:9979da43125ab2530d46250319a101c0$
-- 

return {
	texture = 'PlanetCute_rotated.png',
	frames = {
			{
				name = "Brown Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.897461, u1 = 0.839844, v1 = 0.996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Character Boy.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.897461, u1 = 0.671875, v1 = 0.996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Character Cat Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.897461, u1 = 0.503906, v1 = 0.996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Character Horn Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.897461, u1 = 0.335938, v1 = 0.996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Character Pink Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.897461, u1 = 0.167969, v1 = 0.996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Character Princess Girl.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.797852, u1 = 0.839844, v1 = 0.896484 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Chest Closed.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.797852, u1 = 0.671875, v1 = 0.896484 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Chest Lid.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.797852, u1 = 0.503906, v1 = 0.896484 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Chest Open.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.797852, u1 = 0.335938, v1 = 0.896484 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Dirt Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.797852, u1 = 0.167969, v1 = 0.896484 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Door Tall Closed.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.84082, v0 = 0.672852, u1 = 0.939453, v1 = 0.839844 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Door Tall Open.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.698242, u1 = 0.839844, v1 = 0.796875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Enemy Bug.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.698242, u1 = 0.671875, v1 = 0.796875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Gem Blue.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.698242, u1 = 0.503906, v1 = 0.796875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Gem Green.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.698242, u1 = 0.335938, v1 = 0.796875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Gem Orange.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.698242, u1 = 0.167969, v1 = 0.796875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Grass Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.598633, u1 = 0.839844, v1 = 0.697266 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Heart.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.598633, u1 = 0.671875, v1 = 0.697266 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Key.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.598633, u1 = 0.503906, v1 = 0.697266 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Plain Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.598633, u1 = 0.335938, v1 = 0.697266 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Ramp East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.598633, u1 = 0.167969, v1 = 0.697266 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Ramp North.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.84082, v0 = 0.504883, u1 = 0.939453, v1 = 0.671875 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Ramp South.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.499023, u1 = 0.839844, v1 = 0.597656 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Ramp West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.499023, u1 = 0.671875, v1 = 0.597656 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Rock.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.499023, u1 = 0.503906, v1 = 0.597656 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Roof East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.499023, u1 = 0.335938, v1 = 0.597656 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Roof North East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.499023, u1 = 0.167969, v1 = 0.597656 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Roof North West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.84082, v0 = 0.336914, u1 = 0.939453, v1 = 0.503906 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Roof North.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.399414, u1 = 0.839844, v1 = 0.498047 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Roof South East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.399414, u1 = 0.671875, v1 = 0.498047 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Roof South West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.399414, u1 = 0.503906, v1 = 0.498047 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Roof South.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.399414, u1 = 0.335938, v1 = 0.498047 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Roof West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.399414, u1 = 0.167969, v1 = 0.498047 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Selector.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.299805, u1 = 0.839844, v1 = 0.398438 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.299805, u1 = 0.671875, v1 = 0.398438 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow North East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.299805, u1 = 0.503906, v1 = 0.398438 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow North West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.299805, u1 = 0.335938, v1 = 0.398438 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow North.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.299805, u1 = 0.167969, v1 = 0.398438 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow Side West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.84082, v0 = 0.168945, u1 = 0.939453, v1 = 0.335938 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shadow South East.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.200195, u1 = 0.839844, v1 = 0.298828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow South West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.200195, u1 = 0.671875, v1 = 0.298828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow South.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.200195, u1 = 0.503906, v1 = 0.298828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Shadow West.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.200195, u1 = 0.335938, v1 = 0.298828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "SpeechBubble.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.200195, u1 = 0.167969, v1 = 0.298828 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Star.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.100586, u1 = 0.839844, v1 = 0.199219 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Stone Block Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.100586, u1 = 0.671875, v1 = 0.199219 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Stone Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.100586, u1 = 0.503906, v1 = 0.199219 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Tree Short.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.100586, u1 = 0.335938, v1 = 0.199219 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Tree Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.100586, u1 = 0.167969, v1 = 0.199219 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Tree Ugly.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.84082, v0 = 0.000976562, u1 = 0.939453, v1 = 0.167969 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Wall Block Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.672852, v0 = 0.000976562, u1 = 0.839844, v1 = 0.0996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Wall Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.504883, v0 = 0.000976562, u1 = 0.671875, v1 = 0.0996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Water Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.336914, v0 = 0.000976562, u1 = 0.503906, v1 = 0.0996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Window Tall.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.168945, v0 = 0.000976562, u1 = 0.335938, v1 = 0.0996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Wood Block.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 171 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.167969, v1 = 0.0996094 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

